@startuml
package tracklab-backend as tracklab_backend  {
    ' Bounded Context
    package order {
        package domain {
            package model {
                package aggregates {
                  class Order <<AggregateRoot>> {
                      - Long OrderId
                      - TenantId TenantId  // CustomerId
                      - TenantId LogisticsId  // LogisticsId
                      - String ShippingAddress
                      - Date OrderDate
                      - OrderStatus Status
                      - List<OrderItem> OrderItems
                      + Order(CreateOrderCommand command)
                      + void AddOrderItem(OrderItem item)
                      + void UpdateStatus(OrderStatus status)
                  }
                }
                package commands {
                    class AddOrderItemCommand {
                        + long OrderId
                        + long ProductId
                        + int Quantity
                        + decimal PriceAmount
                        + string PriceCurrency
                    }
                    class CreateOrderCommand {
                        + long CustomerId
                        + long LogisticsId
                        + string ShippingAddress
                    }
                    class DeleteOrderCommand {

                    }
                    class UpdateOrderStatusCommand {
                        + long OrderId
                        + OrderStatus NewStatus
                    }
                }
                package entities{
                  class OrderItem {
                      - Long Id
                      - ProductId ProductId
                      - int Quantity
                      - Price Price
                      + OrderItem(Long productId, int quantity, Price price)
                      + decimal GetTotalPrice()
                  }
                }
                package Queries {
                    class GetAllOrdersQuery {
                        + int? PageSize
                        + int? PageNumber
                        + OrderStatus? Status
                        + long? CustomerId
                        + Datetime? FromDate
                        + DateTime? ToDate
                        + GetAllOrdersQuery(int? pageSize, int? pageNumber, OrderStatus? status, long? customerId, DateTime? fromDate, DateTime? toDate)
                    }
                    class GetOrderByIdQuery {
                        + long Id
                        + GetOrderByIdQuery(long id)
                    }
                }
                package valueobjects {
                    enum OrderStatus {
                        Pending
                        Shipped
                        Delivered
                        Cancelled
                    }
                    class ProductId{
                        + long Value
                        + ProductId()
                        + ProductId(long value)
                        + string ToString()
                        + operator long(ProductId productId)
                        + operator ProductId(long value)
                    }
                }
            }
            package repositories {
                interface IOrderRepository {
                    + Task<IEnumerable<OrderAggregate>> GetAllAsync(GetAllOrdersQuery query)
                    + Task<OrderAggregate?> GetByIdAsync(GetOrderByIdQuery query)
                }
            }
            package services {
                interface IOrderCommandService {
                    + Task<OrderAggregate> CreateAsync(CreateOrderCommand command)
                    + Task<OrderAggregate> AddOrderItemAsync(AddOrderItemCommand command)
                    + Task<OrderAggregate> UpdateStatusAsync(UpdateOrderStatusCommand command)
                    + Task DeleteAsync(DeleteOrderCommand command)
                }
            }
        }
        package infrastructure {
            package persistence {
                package efc {
                    package repositories {
                        class OrderRepository {
                            - ITenantContext _tenantContext
                            + OrderRepository(AppDbContext context, ITenantContext tenantContext)
                            - IQueryable<OrderAggregate> GetTenantFilteredQuery()
                            + Task<IEnumerable<OrderAggregate>> GetAllAsync(GetAllOrdersQuery query)
                            + Task<OrderAggregate?> GetByIdAsync(GetOrderByIdQuery query)
                            + Task<OrderAggregate?> FindByIdAsync(long id)
                        }
                    }
                }
            }
        }
        package application {
            package internal {
                package commandservices {
                    class OrderCommandService {
                        - IOrderRepository _orderRepository
                        + OrderCommandService(IOrderRepository orderRepository)
                        + Task<OrderAggregate> CreateAsync(CreateOrderCommand command)
                        + Task<OrderAggregate> AddOrderItemAsync(AddOrderItemCommand command)
                        + Task<OrderAggregate> UpdateStatusAsync(UpdateOrderStatusCommand command)
                        + Task DeleteAsync(DeleteOrderCommand command)
                    }
                }
                package queryservices {
                    class OrderQueryService {
                        - IOrderRepository _orderRepository
                        + OrderQueryService(IOrderRepository orderRepository)
                        + Task<IEnumerable<OrderAggregate>> Handle(GetAllOrdersQuery query)
                        + Task<OrderAggregate?> Handle(GetOrderByIdQuery query)
                    }
                }
            }
        }
        package interfaces {
            package rest {
                package resources {
                    class AddOrderItemResource {
                        + long ProductId
                        + int Quantity
                        + decimal PriceAmount
                        + string PriceCurrency
                    }
                    class CreateOrderResource {
                        + long CustomerId
                        + long LogisticsId
                        + string ShippingAddress
                    }
                    class OrderResource {
                        + long OrderId
                        + long CustomerId
                        + long LogisticsId
                        + string ShippingAddress
                        + DateTime OrderDate
                        + string Status
                        + decimal TotalPrice
                        + IEnumerable<OrderItemResource> OrderItems
                    }
                    class OrderItemResource {
                        + long Id
                        + long ProductId
                        + int Quantity
                        + decimal PriceAmount
                        + string PriceCurrency
                    }
                    class UpdateOrderStatusResource {
                        string Status
                    }
                }
                package transformers {
                    class AddOrderItemCommandFromResourceAssembler {
                        + AddOrderItemCommand ToCommandFromResource(long orderId, AddOrderItemResource resource)
                    }
                    class CreateOrderCommandFromResourceAssembler {
                        + CreateOrderCommand ToCommandFromResource(CreateOrderResource resource)
                    }
                    class OrderResourceFromEntityAssembler {
                        + OrderResource ToResourceFromEntity(OrderAggregate order)
                        + IEnumerable<OrderResource> ToResourceFromEntities(IEnumerable<OrderAggregate> orders)
                        + OrderItemResource ToOrderItemResourceFromEntity(OrderItem orderItem)
                    }
                    class UpdateOrderStatusCommandFromResourceAssemble {
                        + UpdateOrderStatusCommand ToCommandFromResource(long orderId, UpdateorderStatusResource resource)
                    }
                }
                package controllers {
                    class OrderController {
                        - IOrderCommandService _orderCommandService
                        - IOrderQueryService _orderQueryService
                        + OrderController(IOrderCommandService orderCommandService, IOrderQueryService orderQueryService)
                        + Task<ActionResult<IEnumerable<OrderResource>>> GetAll()
                        + Task<ActionResult<OrderResource>> GetById(long id)
                        + Task<ActionResult<OrderResource>> Create([FromBody] CreateOrderResource resource)
                        + Task<ActionResult<OrderResource>> AddOrderItem(long id, [FromBody] AddOrderItemResource resource)
                        + Task<ActionResult<OrderResource>> UpdateStatus(long id, [FromBody] UpdateOrderStatusResource resource)
                        + Task<ActionResult> Delete(long id)
                    }
                }
            }
        }
    }
    package shared{
        package domain.model{
            package aggregates{
                class Asset <<AggregateRoot>> {
                  - Long Id
                  - TenantId TenantId
                  - String PublicId
                  - String Url
                  + Asset(CreateAssetCommand command)
                }
            }
            package valueobjects {
                class TenantId {
                  -Long Id
                }
                class Price <<ValueObject>> {
                    - BigDecimal Amount
                    - String Currency
                    + Price(BigDecimal amount, String currency)
                }

            }
        }
    }
}


@enduml
