@startuml
package tracklab-backend as tracklab_backend  {
    ' Bounded Context
    package template {
        package domain {
              package model {
                package aggregates {
                  class Order <<AggregateRoot>> {
                      - Long OrderId
                      - TenantId TenantId  // CustomerId
                      - TenantId LogisticsId  // LogisticsId
                      - String ShippingAddress
                      - Date OrderDate
                      - OrderStatus Status
                      - List<OrderItem> OrderItems
                      + Order(CreateOrderCommand command)
                      + void AddOrderItem(OrderItem item)
                      + void UpdateStatus(OrderStatus status)
                  }
                }
                package Entities{
                  class OrderItem {
                      - Long Id
                      - ProductId ProductId  // Referencia al producto desde el ResourceContext
                      - int Quantity
                      - Price Price  // Precio al momento de la compra
                      + OrderItem(Long productId, int quantity, Price price)
                  }
                }
                package valueobjects {
                    enum OrderStatus {
                        Pending
                        Shipped
                        Delivered
                        Cancelled
                    }
                    class ProductId{

                    }
                }
              }
        }
        package infrastructure {
            package persistence {
                package jpa {
                    ' Interfaces que implementan el patrón Repository para la persistencia de datos
                }
            }
        }
        package application {
            package internal {
                package commandservices {
                    ' Clases que implementan las interfaces de servicios de comandos, ejecutando lógica de negocios relacionada con cambios de estado
                }
                package queryservices {
                    ' Clases que implementan las interfaces de servicios de consultas, para la obtención de datos del sistema
                }
            }
        }
        package interfaces {
            package rest {
                package resources {
                    ' Clases de tipo record que funcionan como DTOs (Data Transfer Objects), siguiendo los principios REST (se tratan como recursos)
                }
                package transform {
                    ' Clases con métodos estáticos para mapear entre recursos, comandos, consultas o entidades
                    ' Equivalente al patrón Assembler, puede ser denominado de esta manera
                }
                package controllers {
                    ' Clases que exponen los endpoints REST del sistema, permitiendo la interacción con el cliente
                }
            }
        }
    }
    package shared{
        package domain.model{
            package aggregates{
                class Asset <<AggregateRoot>> {
                  - Long Id
                  - TenantId TenantId
                  - String PublicId
                  - String Url
                  + Asset(CreateAssetCommand command)
                }
            }
            package valueobjects {
                class TenantId {
                  -Long Id
                }
                class Price <<ValueObject>> {
                    - BigDecimal Amount
                    - String Currency
                    + Price(BigDecimal amount, String currency)
                }

            }
        }
    }
}


@enduml
