@startuml
package tracklab-backend as tracklab_backend  {
    package tracking {
        package domain {
            package model {
                package aggregates {
                    class Route <<AggregateRoot>> {
                        - Long RouteId
                        - List<RouteItem> Route  // Lista de nodos (almacenes)
                        - List<OrderId> orders  // Orders que satisface la ruta (puede ser parcialmente)
                        -
                        - VehicleId vehicleId
                        + Route(CreateRouteCommand command)
                        + void AddNode(Node node)
                        + void AddOrder(Order order)
                    }


                    class Container {
                        - Long ContainerId
                        - Long OrderId
                        - List<shipItem> shipItems  // Productos de la orden que se están transportando
                        - WarehouseId warehouseId  // Nodo actual en el que está el container
                        + Container(CreateContainerCommand command)
                        + void UpdateCurrentNode(Node node)
                    }

                    class TrackingEvent {
                        - Long EventId
                        - Long ContainerId
                        - Long WarehouseId // tal vez como VO
                        - EventType Type  // Entrada o salida
                        - Date EventTime  // Hora del evento
                        + TrackingEvent(Long containerId, Long nodeId, EventType type, Date eventTime)
                    }
                }

                package Entities{
                    class RouteItem {
                        - Id
                        - WarehouseId warehouseId
                        - DateTime completedAt
                        - Boolean IsCompleted  // Indica si el nodo fue completado (carga/descarga)
                        + Node()
                        + void MarkAsCompleted()
                    }
                }
                package valueobjects {
                    enum EventType {
                        Arrival  // Cuando un container llega al nodo
                        Departure  // Cuando un container sale del nodo
                        Creation //Momento de creación
                    }
                    class shipItem{
                        Long productId
                        Long quantity
                    }
                }
            }
        }
    }
}
@enduml
